/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    ImgLayout1: typeof import('./src/components/Layout/imgLayout1/index.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/Layout/sub-menu/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
  }
}
