/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMap: typeof import('./src/components/MapChart/AMap.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    ColBar: typeof import('./src/components/ColBar/index.vue')['default']
    DPlayer: typeof import('./src/components/DPlayer/index.vue')['default']
    FlvPlayer: typeof import('./src/components/FlvPlayer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MapChart: typeof import('./src/components/MapChart/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    MTable: typeof import('./src/components/MTable/index.vue')['default']
    Period: typeof import('./src/components/Period/index.vue')['default']
    Progress: typeof import('./src/components/Progress/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolFilter: typeof import('./src/components/SchoolFilter/index.vue')['default']
    Select: typeof import('./src/components/Select/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    WebVideoPlayer: typeof import('./src/components/WebVideoPlayer/index.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper/index.vue')['default']
  }
}
